FROM node:20.11.1 as build

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to /app
COPY package*.json ./

# Copy the current directory contents to /app
COPY . .

# Install app dependencies
RUN npm install -g @angular/cli